#pragma config(Sensor, dgtl1,  limitswitch,    sensorTouch)
#pragma config(Motor,  port2,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           rightMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

	void bothMotors(int x)
{
	motor[rightMotor] = x;
	motor[leftMotor] = x;
}

task main()
{
	int i;
	int x;
	x=0;
	while(x == 0)
	{
		bothMotors(127);
		if(SensorValue(limitswitch) == 1)
			{
				x = 1;
			}
	}
	while(x==1){
		bothMotors(-50);
	}
}
